# Name of your application. Used to uniquely configure containers.
service: chaos-backend

# Name of the container image.
image: kavikapalletenne/chaos-backend

# Deploy to these servers.
servers:
  web:
    - 134.199.155.20

proxy:
  ssl: true
  host: chaos-api.devsoc.cn
  app_port: 8000
  healthcheck:
    path: /
    interval: 5
    timeout: 5

# Credentials for your image host.
registry:
  server: ghcr.io
  username: KavikaPalletenne
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  remote: ssh://root@170.64.167.95

env:
  secret:
    - DATABASE_URL
    - JWT_SECRET
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - GOOGLE_REDIRECT_URI
    - GOOGLE_OAUTH2_URL
    - S3_BUCKET_NAME
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
    - S3_ENDPOINT
    - S3_REGION_NAME
    - DEV_ENV
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - SMTP_HOST
    - SMTP_PORT
    - ROLE_NAME_MAX_CHARS
    - ROLE_DESCRIPTION_MAX_CHARS
    - ROLE_POSITIONS_AVAILABLE_MAX
    - CHAOS_SUPER_USER_EMAIL
