# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en-AU'
reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: true
  enable_prompt_for_ai_agents: false
  path_instructions:
    - path: 'frontend-nextjs/**/*'
      instructions: |
        "Confirm that the code adheres to the following:
        - Proper use of Tanstack Query.
        - Efficient requests to the backend.
        - No hardcoded Tailwind styles like bg-[#ffffff], must use src/app/globals.css to change template.
        - All documentation comments for functions reflect the proper function, inputs and outputs"
    - path: 'backend/server/**/*'
      instructions: |
        "Confirm that the code adheres to the following:
        - SpiceDB spicedb/schema.yaml is reflected in src/spicedb/schema.rs.
        - All permissions in the SpiceDB schema are reflection in src/spicedb/policies.rs.
        - Minimal Postgres queries per request. NO N+1 queries at all are allowed.
        - SpiceDB relationships are properly added into required handlers in src/handler/** as per the schema.
        - All handlers that mutate the database to create or delete a resource that is also stored in SpiceDB, should create or delete the applicable SpiceDB relationships.
        - All documentation comments for functions reflect the proper function, inputs and outputs
        - All handler functions are documented in backend/api.yaml with the correct input and output schemas"
    - path: 'backend/migrations/**/*'
      instructions: |
        "Confirm that the code adheres to the following:
        - Postgres schema best practices.
        - Minimal to no array columns - everything should be normalised.
        - No data duplication between tables."
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - '.*'
    ignore_usernames:
      - 'renovate[bot]'
chat:
  auto_reply: false