# Name of your application. Used to uniquely configure containers.
service: chaos-frontend

# Name of the container image.
image: kavikapalletenne/chaos-frontend

# Deploy to these servers.
servers:
  web:
    - 134.199.155.20

proxy:
  ssl: true
  host: chaos.devsoc.cn
  app_port: 80
  healthcheck:
    path: /
    interval: 5
    timeout: 5

# Credentials for your image host.
registry:
  server: ghcr.io
  username: KavikaPalletenne
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  remote: ssh://root@170.64.167.95

env:
  secret:
    - NEXT_PUBLIC_APP_URL
    - NEXT_API_BASE_URL
    - NEXT_PUBLIC_EDIT_CAMPAIGN_HEADER_MAX_CHARS
    - NEXT_PUBLIC_EDIT_CAMPAIGN_DESCRIPTION_MAX_CHARS
    - NEXT_PUBLIC_EDIT_CAMPAIGN_ROLE_NAME_MAX_CHARS
    - NEXT_PUBLIC_MAX_ROLE_LIMIT

