ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS published BOOLEAN;
UPDATE campaigns SET published = FALSE WHERE published IS NULL;
ALTER TABLE campaigns ALTER COLUMN published SET NOT NULL;
ALTER TABLE campaigns ALTER COLUMN published SET DEFAULT FALSE;