import Providers from "@/app/providers";
import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  const { lang } = await params;
  
  return (
    <html lang={lang}>
      <body>
        <Providers>{children}</Providers>        
      </body>
    </html>
  );
}
